apiVersion: v1
kind: Service
metadata:
  name: {{ include "new-install-notifier.fullname" . }}
  labels:
    {{- include "new-install-notifier.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: 30001
      protocol: TCP
      name: http
  selector:
    {{- include "new-install-notifier.selectorLabels" . | nindent 4 }}
